apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: didp-postgres-pvc
  labels:
    app.kubernetes.io/instance: didp-postgres
    app.kubernetes.io/name: didp-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi