---
apiVersion: v1
kind: Service
metadata:
  name: didp-postgres-service
  labels:
    app.kubernetes.io/instance: didp-postgres
    app.kubernetes.io/name: didp-postgres
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/name: didp-postgresql
  type: ClusterIP
